version: '3'

services:
  php:
    build:
      context: ./docker/php
    volumes:
      - ./bitrix:/var/www/html
      - ./logs/php:/var/log/php
    environment:
      - PHP_MEMORY_LIMIT=512M
      - UPLOAD_MAX_FILESIZE=50M
      - POST_MAX_SIZE=50M
    networks:
      - bitrix-network
    restart: unless-stopped
    depends_on:
      - mysql


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./bitrix:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    networks:
      - bitrix-network
    restart: unless-stopped
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - bitrix-network
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - bitrix-network
    depends_on:
      - mysql
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - bitrix-network
    restart: unless-stopped

networks:
  bitrix-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data:
